import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
import StyledComponentsRegistry from "@/lib/styledComponentsRegistry";
import Theme from "@/lib/Theme";
import { ChakraRegistery } from "@/lib/ChakraRegistery";

import GlobalNavBar from "@/components/organisms/GlobalNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <StyledComponentsRegistry>
            <Theme>
              <ChakraRegistery>
                <GlobalNavBar />
                {children}
              </ChakraRegistery>
            </Theme>
          </StyledComponentsRegistry>
        </AuthContextProvider>
      </body>
    </html>
  );
}
